; ##############################################################
;  Artemis 起動設定ファイル / PS4用
; ##############################################################

; --------------------------------------------------------------
;
; --------------------------------------------------------------
[PS4]

;NP_ID         = NPWR11722
;NP_SUB_ID     = 0
;NP_PASSPHRASE = dbc428ca0d326edeb7753c59b0e71319cda3620d190f585f530f21aa71aa9a22fecfcbb56705bfa0520f919cfbafa37ff261bd563637464bc7763016bae1250e208e350af09836ffb0cc86e3b22fcff0d8b4f306ae2587bef61358c2e2686aca082c350e8ad8f1d3a3913b53e6b3cbda5101516a56e0dc3c8d8e2d051bd13bd8
;NP_SIGNATURE  = b9dde13b0100000000000000711948fbd221ac45eabe2c88494abf91c96aaa11b2f0230ee668116938096698663238f344ed8129579cbbd8a6bf19d4243a06e0900c750f5d82354a6d4dff6f8486c5147a36a4a95245acb4e3591b7ba293f43654b495ae95417e1142c942b1651527c7dca856f20728fda1eb3343cf8d8850013ec0d28cfb841885b437b1baa687e3bb52a66c2b9b407ad894bc31352d9c6421

SAVE_TITLE     = 千の刃濤、桃花染の皇姫
SAVE_SUB_TITLE = セーブデータ
SAVE_DETAIL    = 千の刃濤、桃花染の皇姫のセーブデータです。
SAVE_ICON_PATH = app0:saveicon.png

; 文字コード
CHARSET = UTF-8

; ステージの幅
WIDTH = 1920
; ステージの高さ
HEIGHT = 1080

; ステージと液晶パネルの縦横比が一致しない場合に
; はみ出した部分をカットしてフィットさせるか否か
SIDECUT = 0

; 最初に読み込むスクリプト
BOOT = system/first.iet

; フォントキャッシュ（本文とバックログのパフォーマンス要チェック）
;FONT_CACHE_SIZE = 50331648
;FONT_CACHE_SIZE = 33554432
;FONT_CACHE_SIZE = 25165824
;FONT_CACHE_SIZE = 16777216

; --------------------------------------------------------------
;  Windows版の設定
; --------------------------------------------------------------
[WINDOWS]

; ステージの幅 (起動時のウィンドウの幅もこの値になる)
WIDTH = 1920
; ステージの高さ (起動時のウィンドウの高さもこの値になる)
HEIGHT = 1080
; フレームレート
FPS = 60

; 文字コード
CHARSET = UTF-8

; ウィンドウに枠を付けるか否か
FRAMELESS = 0

; ウィンドウをリサイズ可能にするか否か
RESIZABLE = 1

; ウィンドウをリサイズしたときに縦横比を固定するか否か
FIXED_ASPECT_RATIO = 1

; ウィンドウのリサイズやフルスクリーン化によって
; ステージとウィンドウの縦横比が一致しなくなった場合に
; はみ出した部分をカットしてフィットさせるか否か
SIDECUT = 0

; ソフトウェアレンダリングを強制するか否か
FORCE_SOFTWARE_RENDER = 0

; 最初に読み込むスクリプト
BOOT = system/first.iet

; セーブデータの保存先フォルダ
SAVEPATH = savedata

; セーブデータの保存先フォルダ：C:\Users\hoge\AppData\Roaming\maker\title
;SAVEPATH = メーカー\タイトル
;SAVEPATH_CSIDL = 26

; 画像キャッシュの設定
; 64MB
;SURFACE_CACHE_SIZE = 67108864

;SHADER = 0

; --------------------------------------------------------------
; Switch用の設定
; --------------------------------------------------------------
[SWITCH]

; 文字コード
CHARSET = UTF-8

; ステージの幅
WIDTH = 1920
; ステージの高さ
HEIGHT = 1080

; ステージと液晶パネルの縦横比が一致しない場合に
; はみ出した部分をカットしてフィットさせるか否か
SIDECUT = 0

; 最初に読み込むスクリプト
BOOT = system/first.iet

; フォントキャッシュ（本文とバックログのパフォーマンス要チェック）
;FONT_CACHE_SIZE = 50331648
;FONT_CACHE_SIZE = 33554432
FONT_CACHE_SIZE = 25165824
;FONT_CACHE_SIZE = 16777216
;FONT_CACHE_SIZE = 14680064
;FONT_CACHE_SIZE = 67108864

; --------------------------------------------------------------
